### ISSUE TITLE
Another repo transfer?

### ISSUE THREAD

**Issue by k-dominik** [ilastik/hytra#36]
Hi @chaubold,

how could this one slip?! Would you mind transferring this also to the ilastik org?

Cheers
Dominik

**Comment by k-dominik** [comment]
Hello @chaubold, happy new year ;). I'm bumping this issue, as it would be really great to have all the repos in the ilastik org...

**Comment by chaubold** [comment]
Argh, sorry @k-dominik, I didn't notice your request 😢. I should sign in to GitHub more often 😬 Transferring it now 👋

**Comment by k-dominik** [comment]
thank you so much @chaubold!!! Sad to hear you're not spending a lot of time on github - world needs your coding! :)

**Comment by chaubold** [comment]
we develop in bitbucket and sync to GitHub so... my code is still here 😆
Best wishes from Konstanz!
